server:
  port: 8080
spring:
  application:
    name: zuulserver
  cloud:
    consul:
      host: 192.168.254.130 #consul的host地址
      port: 8500
      discovery:
        register: true    #是否注册到consul中
        instance-id: zuulserver01 #网关也要配置多个,单点是瓶颈
        prefer-ip-address: true
        health-check-interval: 15s
        hostname: 10.39.4.95 #服务的host地址
        service-name: ${spring.application.name}
        enabled: true
zuul:
  #网关前缀,设置后所有请求都必须以 /lujieni 开头
  prefix: /lujieni
  routes:
    hello: #hello只是给路由起个名字
      service-id: sayportservice #sayportservice为consul中注册的服务名
      path: /wahaha/**  # /lujieni/wahaha/zuul & /lujieni/sayportservice/zuul 都可以访问,因为默认基于consul中服务的代理也是生效的,除非ignored-services: '*'
  sensitive-headers:    # 敏感的请求头为空,这样设置后Cookie才可以被正确传递
  ignored-services: '*'
hystrix:
  command:
    default: #如果要通过特定的服务,改成对应服务id
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000 #60秒超时,hystrix激活
ribbon:
  #默认情况下,GET方式请求无论是连接异常还是读取异常,都会进行重试;非GET方式请求,只有连接异常时,才会进行重试
  ReadTimeout: 60000
  ConnectTimeout: 10000
  OkToRetryOnAllOperations: false #只会对get请求进行重试(连接,读取) post方式重试(连接)
  MaxAutoRetries: 1 #如果不配置ribbon的重试次数，默认会重试一次
  MaxAutoRetriesNextServer: 0     #不会发给另一个实例
  httpclient:
    enabled: false
  okhttp:
    enabled: true