server:
  port: 8080
spring:
  application:
    name: zuulserver
  cloud:
    consul:
      host: 192.168.254.130 #consul的host地址
      port: 8500
      discovery:
        register: true    #是否注册到consul中
        instance-id: zuulserver01 #网关也要配置多个,单点是瓶颈
        prefer-ip-address: true
        health-check-interval: 15s
        hostname: 10.39.4.95 #服务的host地址
        service-name: ${spring.application.name}
        enabled: true
zuul:
  #网关前缀,设置后所有请求都必须以 /lujieni 开头
  prefix: /lujieni
  routes:
    hello: #hello只是给路由起个名字
      service-id: sayportservice #sayportservice为consul中注册的服务名
      path: /wahaha/**  # /lujieni/wahaha/zuul & /lujieni/sayportservice/zuul 都可以访问,因为默认基于consul中服务的代理也是生效的,除非ignored-services: '*'
  sensitive-headers:    # 敏感的请求头为空,这样设置后Cookie才可以被正确传递
  ignored-services: '*'
hystrix:
  command:
    default: #如果要通过特定的服务,改成对应服务id
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 40000 #2.5秒超时,hystrix激活
