server:
  port: 8080
spring:
  application:
    name: zuulserver
  cloud:
    consul:
      host: 192.168.254.130 #consul的host地址
      port: 8500
      discovery:
        register: true    #是否注册到consul中
        instance-id: zuulserver01 #网关也要配置多个,单点是瓶颈
        prefer-ip-address: false #是否显示ip地址
        health-check-interval: 15s
        hostname: 10.39.4.65 #服务的host地址
        service-name: ${spring.application.name}
        enabled: true
zuul:
  #网关前缀,设置后所有请求都必须以 /lujieni 开头
  prefix: /lujieni
  routes:
    hello: #hello只是给路由起个名字
      service-id: sayportservice #sayportservice为consul中注册的服务名
      path: /wahaha/**  # /lujieni/wahaha/love/zuul & /lujieni/sayportservice/love/zuul 都可以访问,因为默认基于consul中服务的代理也是生效的,除非ignored-services: '*'
  ignored-services: "*" # *代表所有的服务都不能使用微服务名字去访问
  sensitive-headers:    # 敏感的请求头为空,这样设置后Cookie才可以被zuul正确传递到下级服务

ribbon:
  ReadTimeout: 3000  #请求处理的超时时间
  ConnectTimeout: 2000  #请求连接的超时时间